# Railway 部署配置文件
# ZeroTouch Services 项目

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

# Railway 会自动设置 PORT 环境变量
[variables]
NODE_ENV = "production"
VITE_APP_TITLE = "ZeroTouch Services"

# 如果需要指定启动命令（通常 Dockerfile 已包含）
# startCommand = "nginx -g 'daemon off;'"
