name: Deploy to Railway

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Test Railway Dockerfile
        run: |
          docker build -f Dockerfile.railway -t zerotouch-test .
          docker run -d -p 3000:3000 -e PORT=3000 --name zerotouch-test-container zerotouch-test
          sleep 10
          curl -f http://localhost:3000/health || exit 1
          docker stop zerotouch-test-container
          docker rm zerotouch-test-container

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Wait for deployment
        run: sleep 30

      - name: Health check
        run: |
          # 这里需要替换为你的实际 Railway 应用 URL
          # curl -f ${{ secrets.RAILWAY_APP_URL }}/health || exit 1
          echo "请在 Railway 控制台确认部署状态"
